name: 触发compile启动编译
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '编译OpenWrt固件-SSH远程：改为"ssh"打开SSH连接'
        required: true
        default: 'ssh-actions'


jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: 准备结束
      uses: actions/checkout@v2

    - name: SSH远程连接服务器
      uses: P3TERX/ssh2actions@v1.0.0
      if: env.SSH_ACTIONS == 'true' || (github.event.inputs.ssh == 'ssh' && github.event.inputs.ssh  != 'false')
      env:
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
