name: 编译openwrt固件

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  schedule:
    - cron:  1 0 * * 6
  
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: 准备开始
      uses: actions/checkout@main
      
    - name: 清理磁盘空间
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: 安装系统依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update
        sudo -E apt-get -qq install ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential \
        bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib \
        git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev \
        libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz \
        mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools \
        libpython3-dev qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip \
        vim wget xmlto xxd zlib1g-dev python3-setuptools
        sudo -E apt-get -qq autoremove --purge
        sudo -E apt-get -qq clean
        sudo rm -rf /etc/apt/sources.list.d/* /usr/local/lib/android /opt/ghc /usr/share/dotnet /usr/local/graalvm /usr/local/.ghcup \
        /usr/local/share/powershell /usr/local/share/chromium /usr/local/lib/node_modules
        sudo -E systemctl daemon-reload
        sudo -E timedatectl set-timezone "Asia/Shanghai"
        
    - name: 下载固件源码
      working-directory: ./
      run: |
        # 下载固件源码
        git clone https://github.com/coolsnowwolf/lede

    - name: 更新和安装软件包
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        
    - name: 常用配置修改
      run: |
        cd lede
        git clone https://github.com/kenzok8/openwrt-packages package/zheng
        git clone https://github.com/kenzok8/small package/zheng/passwall
        rm -rf package/zheng/passwall/luci-app-passwall2 package/zheng/passwall/luci-app-ssr-plus package/zheng/passwall/luci-app-bypass
        git clone https://github.com/fw876/helloworld package/zheng/ssrplus
        sed -i "s/192.168.1.1/192.168.2.3/g" package/base-files/files/bin/config_generate
        sed -i 's/ShadowSocksR Plus+/SSR Plus+/g' package/zheng/ssrplus/luci-app-ssr-plus/luasrc/controller/shadowsocksr.lua
        sed -i 's/TTYD 终端/命令行/g' feeds/luci/applications/luci-app-ttyd/po/zh-cn/terminal.po
  
    - name: 配置固件文件
      run: |
        cd lede
        rm -f ./.config*
        touch ./.config
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        CONFIG_CGROUPFS_MOUNT_KERNEL_CGROUPS=y
        CONFIG_DOCKER_CGROUP_OPTIONS=y
        CONFIG_DOCKER_NET_MACVLAN=y
        CONFIG_DOCKER_OPTIONAL_FEATURES=y
        CONFIG_DOCKER_STO_EXT4=y
        # CONFIG_GRUB_EFI_IMAGES is not set
        CONFIG_GRUB_IMAGES=y
        CONFIG_KERNEL_CFQ_GROUP_IOSCHED=y
        CONFIG_KERNEL_CGROUP_DEVICE=y
        CONFIG_KERNEL_CGROUP_FREEZER=y
        CONFIG_KERNEL_CGROUP_HUGETLB=y
        CONFIG_KERNEL_CGROUP_NET_PRIO=y
        CONFIG_KERNEL_CGROUP_PERF=y
        CONFIG_KERNEL_HUGETLBFS=y
        CONFIG_KERNEL_HUGETLB_PAGE=y
        CONFIG_KERNEL_MEMCG_SWAP_ENABLED=y
        CONFIG_KERNEL_NET_CLS_CGROUP=y
        CONFIG_KERNEL_PERF_EVENTS=y
        CONFIG_KERNEL_TRANSPARENT_HUGEPAGE=y
        CONFIG_KERNEL_TRANSPARENT_HUGEPAGE_ALWAYS=y
        CONFIG_OPENSSH_LIBFIDO2=y
        # CONFIG_PACKAGE_TURBOACC_INCLUDE_BBR_CCA is not set
        CONFIG_PACKAGE_autossh=y
        CONFIG_PACKAGE_avahi-dbus-daemon=y
        CONFIG_PACKAGE_bash=y
        CONFIG_PACKAGE_blkid=y
        CONFIG_PACKAGE_boost=y
        CONFIG_PACKAGE_boost-program_options=y
        CONFIG_PACKAGE_boost-system=y
        CONFIG_PACKAGE_btrfs-progs=y
        CONFIG_PACKAGE_cgroupfs-mount=y
        CONFIG_PACKAGE_chinadns-ng=y
        CONFIG_PACKAGE_containerd=y
        CONFIG_PACKAGE_coreutils-nohup=y
        CONFIG_PACKAGE_dbus=y
        CONFIG_PACKAGE_docker=y
        CONFIG_PACKAGE_docker-compose=y
        CONFIG_PACKAGE_dockerd=y
        # CONFIG_PACKAGE_etherwake is not set
        # CONFIG_PACKAGE_grub2-efi is not set
        CONFIG_PACKAGE_haproxy=y
        CONFIG_PACKAGE_hysteria=y
        CONFIG_PACKAGE_ipt2socks=y
        CONFIG_PACKAGE_kmod-br-netfilter=y
        CONFIG_PACKAGE_kmod-crypto-acompress=y
        CONFIG_PACKAGE_kmod-dummy=y
        CONFIG_PACKAGE_kmod-fs-btrfs=y
        CONFIG_PACKAGE_kmod-inet-diag=y
        # CONFIG_PACKAGE_kmod-ipt-offload is not set
        CONFIG_PACKAGE_kmod-ipt-physdev=y
        CONFIG_PACKAGE_kmod-lib-lzo=y
        CONFIG_PACKAGE_kmod-lib-raid6=y
        CONFIG_PACKAGE_kmod-lib-xor=y
        CONFIG_PACKAGE_kmod-lib-zlib-deflate=y
        CONFIG_PACKAGE_kmod-lib-zstd=y
        CONFIG_PACKAGE_kmod-netlink-diag=y
        # CONFIG_PACKAGE_kmod-nf-conntrack-netlink is not set
        # CONFIG_PACKAGE_kmod-nf-flow is not set
        CONFIG_PACKAGE_kmod-nf-ipvs=y
        # CONFIG_PACKAGE_kmod-tcp-bbr is not set
        CONFIG_PACKAGE_kmod-veth=y
        CONFIG_PACKAGE_libatomic=y
        CONFIG_PACKAGE_libattr=y
        CONFIG_PACKAGE_libavahi-dbus-support=y
        CONFIG_PACKAGE_libcap=y
        CONFIG_PACKAGE_libcap-bin=y
        CONFIG_PACKAGE_libcap-bin-capsh-shell="/bin/sh"
        CONFIG_PACKAGE_libcbor=y
        CONFIG_PACKAGE_libdaemon=y
        CONFIG_PACKAGE_libdbus=y
        CONFIG_PACKAGE_libeudev=y
        CONFIG_PACKAGE_libevent2=y
        CONFIG_PACKAGE_libexpat=y
        CONFIG_PACKAGE_libfido2=y
        CONFIG_PACKAGE_libgmp=y
        CONFIG_PACKAGE_libltdl=y
        CONFIG_PACKAGE_liblua5.3=y
        CONFIG_PACKAGE_liblzma=y
        CONFIG_PACKAGE_liblzo=y
        CONFIG_PACKAGE_libparted=y
        CONFIG_PACKAGE_libruby=y
        CONFIG_PACKAGE_libseccomp=y
        CONFIG_PACKAGE_libssh=y
        CONFIG_PACKAGE_libstdcpp=y
        CONFIG_PACKAGE_libuv=y
        CONFIG_PACKAGE_libwebsockets-full=y
        CONFIG_PACKAGE_libyaml=y
        # CONFIG_PACKAGE_luci-app-accesscontrol is not set
        CONFIG_PACKAGE_luci-app-adguardhome=y
        # CONFIG_PACKAGE_luci-app-arpbind is not set
        # CONFIG_PACKAGE_luci-app-autoreboot is not set
        # CONFIG_PACKAGE_luci-app-ddns is not set
        CONFIG_PACKAGE_luci-app-diskman=y
        CONFIG_PACKAGE_luci-app-dockerman=y
        # CONFIG_PACKAGE_luci-app-nlbwmon is not set
        CONFIG_PACKAGE_luci-app-openclash=y
        CONFIG_PACKAGE_luci-app-passwall=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Haproxy=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Hysteria=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_ShadowsocksR_Libev_Client=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Client=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Shadowsocks_Libev_Server=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Simple_Obfs=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_SingBox=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Trojan_Plus=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_V2ray_Plugin=y
        CONFIG_PACKAGE_luci-app-passwall_INCLUDE_Xray=y
        CONFIG_PACKAGE_luci-app-passwall_Iptables_Transparent_Proxy=y
        # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
        # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
        CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_ChinaDNS_NG=y
        CONFIG_PACKAGE_luci-app-ssr-plus_INCLUDE_Hysteria=y
        CONFIG_PACKAGE_luci-app-ttyd=y
        # CONFIG_PACKAGE_luci-app-turboacc is not set
        # CONFIG_PACKAGE_luci-app-upnp is not set
        # CONFIG_PACKAGE_luci-app-vlmcsd is not set
        # CONFIG_PACKAGE_luci-app-vsftpd is not set
        # CONFIG_PACKAGE_luci-app-wol is not set
        CONFIG_PACKAGE_luci-i18n-adguardhome-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-diskman-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-dockerman-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-passwall-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-ttyd-zh-cn=y
        CONFIG_PACKAGE_luci-lib-docker=y
        CONFIG_PACKAGE_luci-theme-atmaterial_new=y
        CONFIG_PACKAGE_luci-theme-material=y
        # CONFIG_PACKAGE_miniupnpd is not set
        CONFIG_PACKAGE_mount-utils=y
        CONFIG_PACKAGE_msgpack-c=y
        # CONFIG_PACKAGE_nlbwmon is not set
        CONFIG_PACKAGE_openssh-client=y
        CONFIG_PACKAGE_openssh-client-utils=y
        CONFIG_PACKAGE_openssh-keygen=y
        CONFIG_PACKAGE_openssh-moduli=y
        CONFIG_PACKAGE_openssh-server=y
        CONFIG_PACKAGE_openssh-sftp-avahi-service=y
        CONFIG_PACKAGE_openssh-sftp-client=y
        CONFIG_PACKAGE_openssh-sftp-server=y
        CONFIG_PACKAGE_parted=y
        CONFIG_PACKAGE_ruby=y
        CONFIG_PACKAGE_ruby-bigdecimal=y
        CONFIG_PACKAGE_ruby-date=y
        CONFIG_PACKAGE_ruby-digest=y
        CONFIG_PACKAGE_ruby-enc=y
        CONFIG_PACKAGE_ruby-forwardable=y
        CONFIG_PACKAGE_ruby-pstore=y
        CONFIG_PACKAGE_ruby-psych=y
        CONFIG_PACKAGE_ruby-stringio=y
        CONFIG_PACKAGE_ruby-strscan=y
        CONFIG_PACKAGE_ruby-yaml=y
        CONFIG_PACKAGE_runc=y
        CONFIG_PACKAGE_shadowsocks-libev-ss-local=y
        CONFIG_PACKAGE_shadowsocks-libev-ss-redir=y
        CONFIG_PACKAGE_sing-box=y
        CONFIG_PACKAGE_smartmontools=y
        CONFIG_PACKAGE_sshtunnel=y
        CONFIG_PACKAGE_tini=y
        CONFIG_PACKAGE_tmate=y
        CONFIG_PACKAGE_trojan-plus=y
        CONFIG_PACKAGE_ttyd=y
        CONFIG_PACKAGE_unzip=y
        CONFIG_PACKAGE_v2ray-plugin=y
        # CONFIG_PACKAGE_vlmcsd is not set
        # CONFIG_PACKAGE_vsftpd-alt is not set
        CONFIG_PACKAGE_xz=y
        CONFIG_PACKAGE_xz-utils=y
        CONFIG_PARTED_READLINE=y
        CONFIG_SING_BOX_WITH_CLASH_API=y
        CONFIG_SING_BOX_WITH_DHCP=y
        CONFIG_SING_BOX_WITH_ECH=y
        CONFIG_SING_BOX_WITH_GVISOR=y
        CONFIG_SING_BOX_WITH_QUIC=y
        CONFIG_SING_BOX_WITH_UTLS=y
        CONFIG_SING_BOX_WITH_WIREGUARD=y
        # CONFIG_TARGET_IMAGES_GZIP is not set
        CONFIG_TARGET_KERNEL_PARTSIZE=200
        CONFIG_TARGET_ROOTFS_PARTSIZE=700
        # CONFIG_VMDK_IMAGES is not set
        CONFIG_boost-compile-visibility-hidden=y
        CONFIG_boost-runtime-shared=y
        CONFIG_boost-static-and-shared-libs=y
        CONFIG_boost-variant-release=y
        EOF
        sed -i 's/^[ \t]*//g' ./.config
        make defconfig

    - name: 下载DL库
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;
        
    - name: 开始编译固件
      run: |
        cd lede
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s

    - name: 上传固件
      uses: actions/upload-artifact@main
      with:
        name: OpenWrt
        path: lede/bin/targets/x86/64/*.img
