name: 编译openwrt固件

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  schedule:
    - cron:  1 0 * * 6
  
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: 准备开始
      uses: actions/checkout@main

    - name: 安装系统依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo apt update -y
        sudo apt full-upgrade -y
        sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp nano ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pip qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

    - name: 下载固件源码和软件包
      run: |
        git clone https://github.com/coolsnowwolf/lede
        cd lede
        git clone https://github.com/zjt37/zheng package/zheng/theme
        svn co https://github.com/vernesong/OpenClash/trunk/luci-app-openclash package/zheng/luci-app-openclash
        git clone https://github.com/fw876/helloworld package/zheng/ssrplu

    - name: 更新和安装软件包
      run: |
        cd lede
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        ./scripts/feeds install -a
        
    - name: 常用配置修改
      run: |
        cd lede
        # 修改默认IP
        sed -i "s/192.168.1.1/192.168.1.3/g" package/base-files/files/bin/config_generate
        #  修改默认主题
        sed -i "s/bootstrap/atmaterial/g" feeds/luci/collections/luci/Makefile
        # 汉化实时监控
        rm -rf ./feeds/luci/applications/luci-app-netdata/  
        git clone https://github.com/Jason6111/luci-app-netdata ./feeds/luci/applications/luci-app-netdata/ 
        #  删除主题
        rm -rf ./feeds/freifunk/themes
        rm -rf ./feeds/luci/themes/luci-theme-bootstrap
        rm -rf ./feeds/luci/themes/luci-theme-argon
        rm -rf ./feeds/luci/themes/luci-theme-netgear
        rm -rf ./feeds/luci/themes/luci-theme-material
        # 调整网络共享到系统菜单
        sed -i 's/\"services\"/\"status\"/g' feeds/luci/applications/luci-app-samba/luasrc/controller/samba.lua
        

    - name: 配置固件文件
      run: |
        cd lede
        rm -f ./.config*
        touch ./.config
        cat >> .config <<EOF
        CONFIG_TARGET_x86=y
        CONFIG_TARGET_x86_64=y
        CONFIG_TARGET_x86_64_DEVICE_generic=y
        # CONFIG_GRUB_CONSOLE is not set
        CONFIG_GRUB_IMAGES=y
        # CONFIG_PACKAGE_UnblockNeteaseMusic-Go is not set
        # CONFIG_PACKAGE_adbyby is not set
        CONFIG_PACKAGE_blkid=y
        CONFIG_PACKAGE_btrfs-progs=y
        CONFIG_PACKAGE_dnsforwarder=y
        CONFIG_PACKAGE_dnsproxy=y
        # CONFIG_PACKAGE_etherwake is not set
        # CONFIG_PACKAGE_iptables-mod-ipsec is not set
        # CONFIG_PACKAGE_kmod-crypto-cbc is not set
        # CONFIG_PACKAGE_kmod-crypto-deflate is not set
        # CONFIG_PACKAGE_kmod-crypto-des is not set
        # CONFIG_PACKAGE_kmod-crypto-echainiv is not set
        # CONFIG_PACKAGE_kmod-crypto-hmac is not set
        # CONFIG_PACKAGE_kmod-crypto-kpp is not set
        # CONFIG_PACKAGE_kmod-crypto-md5 is not set
        CONFIG_PACKAGE_kmod-fs-btrfs=y
        # CONFIG_PACKAGE_kmod-ipsec is not set
        # CONFIG_PACKAGE_kmod-ipt-ipsec is not set
        # CONFIG_PACKAGE_kmod-ipt-offload is not set
        # CONFIG_PACKAGE_kmod-iptunnel6 is not set
        CONFIG_PACKAGE_kmod-lib-raid6=y
        CONFIG_PACKAGE_kmod-lib-xor=y
        CONFIG_PACKAGE_kmod-lib-zstd=y
        CONFIG_PACKAGE_kmod-md-mod=y
        CONFIG_PACKAGE_kmod-md-raid0=y
        CONFIG_PACKAGE_kmod-md-raid1=y
        CONFIG_PACKAGE_kmod-md-raid10=y
        CONFIG_PACKAGE_kmod-md-raid456=y
        # CONFIG_PACKAGE_kmod-nf-flow is not set
        CONFIG_PACKAGE_kmod-shortcut-fe=y
        CONFIG_PACKAGE_kmod-shortcut-fe-cm=y
        # CONFIG_PACKAGE_kmod-wireguard is not set
        CONFIG_PACKAGE_libattr=y
        CONFIG_PACKAGE_liblzo=y
        # CONFIG_PACKAGE_libminiupnpc is not set
        # CONFIG_PACKAGE_libnatpmp is not set
        CONFIG_PACKAGE_lsblk=y
        # CONFIG_PACKAGE_luci-app-accesscontrol is not set
        # CONFIG_PACKAGE_luci-app-adbyby-plus is not set
        # CONFIG_PACKAGE_luci-app-arpbind is not set
        # CONFIG_PACKAGE_luci-app-autoreboot is not set
        # CONFIG_PACKAGE_luci-app-ddns is not set
        CONFIG_PACKAGE_luci-app-diskman=y
        CONFIG_PACKAGE_luci-app-diskman_INCLUDE_kmod_md_linear=y
        CONFIG_PACKAGE_luci-app-diskman_INCLUDE_kmod_md_raid456=y
        CONFIG_PACKAGE_luci-app-diskman_INCLUDE_mdadm=y
        # CONFIG_PACKAGE_luci-app-ipsec-vpnd is not set
        CONFIG_PACKAGE_luci-app-netdata=y
        CONFIG_PACKAGE_luci-app-openclash=y
        # CONFIG_PACKAGE_luci-app-ramfree is not set
        # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-ng is not set
        # CONFIG_PACKAGE_luci-app-rclone_INCLUDE_rclone-webui is not set
        CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_DNSFORWARDER=y
        CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_DNSPROXY=y
        CONFIG_PACKAGE_luci-app-turboacc_INCLUDE_SHORTCUT_FE=y
        # CONFIG_PACKAGE_luci-app-unblockmusic is not set
        # CONFIG_PACKAGE_luci-app-unblockmusic_INCLUDE_UnblockNeteaseMusic_Go is not set
        # CONFIG_PACKAGE_luci-app-upnp is not set
        # CONFIG_PACKAGE_luci-app-vlmcsd is not set
        # CONFIG_PACKAGE_luci-app-vsftpd is not set
        # CONFIG_PACKAGE_luci-app-wireguard is not set
        # CONFIG_PACKAGE_luci-app-wol is not set
        # CONFIG_PACKAGE_luci-app-xlnetacc is not set
        # CONFIG_PACKAGE_luci-app-zerotier is not set
        CONFIG_PACKAGE_luci-i18n-diskman-zh-cn=y
        CONFIG_PACKAGE_luci-i18n-netdata-zh-cn=y
        # CONFIG_PACKAGE_luci-proto-wireguard is not set
        CONFIG_PACKAGE_mdadm=y
        # CONFIG_PACKAGE_miniupnpd is not set
        CONFIG_PACKAGE_netdata=y
        CONFIG_PACKAGE_parted=y
        CONFIG_PACKAGE_smartmontools=y
        # CONFIG_PACKAGE_strongswan is not set
        # CONFIG_PACKAGE_vlmcsd is not set
        # CONFIG_PACKAGE_vsftpd-alt is not set
        # CONFIG_PACKAGE_wireguard-tools is not set
        # CONFIG_PACKAGE_wol is not set
        # CONFIG_PACKAGE_zerotier is not set
        CONFIG_TARGET_KERNEL_PARTSIZE=32
        CONFIG_TARGET_ROOTFS_PARTSIZE=600
        # CONFIG_VMDK_IMAGES is not set
        EOF
        sed -i 's/^[ \t]*//g' ./.config
        make defconfig


    - name: 下载DL库
      run: |
        cd lede
        make download -j8
        find dl -size -1024c -exec ls -l {} \;
        find dl -size -1024c -exec rm -f {} \;

    
        
    - name: 开始编译固件
      run: |
        cd lede
        echo -e "$(nproc) thread build."
        make -j$(nproc) V=s
        
  
    - name: 整理发布文件
      id: assemble_artifact
      run: |
         mkdir openwrt
         cp -f "lede/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined.img" "./openwrt/openwrt-x86-64-generic-squashfs-combined.img"
         cp -f "lede/bin/targets/x86/64/openwrt-x86-64-generic-squashfs-combined-efi.img" "./openwrt/openwrt-x86-64-generic-squashfs-combined-efi.img"
         zip OpenWrt.zip ./openwrt/*
         release_tag="openwrt-$(date +%Y-%m-%d)"
         echo "##[set-output name=release_tag;]$release_tag" 
         
    - name: 配置发布信息
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHU_TOKEN }}
      with:
        tag_name: ${{ steps.assemble_artifact.outputs.release_tag }}
        release_name: ${{ steps.assemble_artifact.outputs.release_tag }}
        draft: false
        prerelease: false
        
    - name: 发布固件到Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHU_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: OpenWrt.zip
        asset_name: OpenWrt.zip
        asset_content_type: application/zip

       
