name: 编译PVE

on: 
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'true'

jobs:
  build:
    runs-on: ubuntu-latest
    

    steps:
    - name: 准备开始
      uses: actions/checkout@main

    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        apt-get install devscripts asciidoc-base automake bc bison cpio dh-python bison flex git kmod libdw-dev libelf-dev libiberty-dev libnuma-dev libpve-common-perl libslang2-dev libssl-devlibtool lintian lz4 perl-modules rsync sphinx-common xmlto zlib1g-dev dwarves net-tools htop vnstat        apt-get autoremove --purge
        
