name: 编译PVE内核

on: 
  release:
    types: [published]

  #push:
  #  branches: 
  #    - master

  schedule:
    - cron:  1 0 * * 6
  
  watch:
    types: [started]
    

jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: 准备开始
      uses: actions/checkout@v2

    - name: 清理磁盘空间
      uses: easimon/maximize-build-space@master
      with: 
        root-reserve-mb: 2048
        swap-size-mb: 1
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'

    - name: 安装依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        #sudo wget -qO - http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -  
        sudo wget http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
        sudo chmod +r /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
        sudo chmod a+w /etc/apt/sources.list
        sudo -E echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" >>/etc/apt/sources.list
        sudo -E apt-get  update
        sudo -E apt-get  install git nano screen patch fakeroot build-essential devscripts libncurses5 libncurses5-dev libssl-dev bc flex bison libelf-dev libaudit-dev libgtk2.0-dev libperl-dev asciidoc xmlto gnupg gnupg2 rsync lintian debhelper libdw-dev libnuma-dev libslang2-dev sphinx-common asciidoc-base automake cpio dh-python file gcc kmod libiberty-dev  libtool perl-modules python3-minimal sed tar zlib1g-dev liblz4-tool idn 
        sudo -E apt-get  autoremove --purge
        sudo -E apt-get  clean

    - name:  安装proxmox依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get install libpve-common-perl  dwarves
        git clone https://github.com/acmel/dwarves.git
        cd dwarves/
        mkdir build
        cd build/
        cmake -D__LIB=lib ..
        sudo make install
        sudo cp pahole /usr/bin/pahole
        #sudo cp -r /usr/local/lib/* /usr/lib/

    - name: 下载源码
      working-directory: ./
      run: |
        git clone git://git.proxmox.com/git/pve-kernel.git pve-kernel

    - name: 修改ACS
      run: |
        cd pve-kernel
        sed -i "s/106 @@/105 @@/g" patches/kernel/0004-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch
        sed -i "/pci_find_ext_capability(dev, PCI_EXT_CAP_ID_ACS))/d" patches/kernel/0004-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch
        sed -i "s/(dev) ||/(dev))/g" patches/kernel/0004-pci-Enable-overrides-for-missing-ACS-capabilities-4..patch

    - name: Fix lz4 build deps
      run: |
        cd pve-kernel
        #sed -i "s/lz4/liblz4-1/g" debian/control.in
    
    - name: Fix DEBUG_INFO_BTF
      run: |
        cd pve-kernel
        sed -i 's/${LINUX_TOOLS_DBG_DEB}//' Makefile
        #sed -i "s/-e CONFIG_PAGE_TABLE_ISOLATION/-e CONFIG_PAGE_TABLE_ISOLATION \\\ \n-d CONFIG_DEBUG_INFO_BTF/" debian/rules
    
    - name: Freeing up disk space on CI system
      run: |
        dpkg-query -Wf '${Installed-Size}\t${Package}\n' | sort -n | tail -n 100
        df -h
        sudo apt-get remove -y '^ghc-8.*'
        sudo apt-get remove -y '^dotnet-.*'
        sudo apt-get remove -y '^llvm-.*'
        sudo apt-get remove -y 'php.*'
        sudo apt-get remove -y azure-cli google-cloud-sdk hhvm google-chrome-stable firefox powershell mono-devel
        sudo apt-get autoremove -y
        sudo apt-get clean
        df -h
        rm -rf /usr/share/dotnet/
        df -h

    - name: Compile the PVE kernel
      id: compile
      run: |
        cd pve-kernel
        echo -e "$(nproc) thread compile"
        make -j$(nproc) || make -j1 V=s
        echo "::set-output name=status::success"

    - name: 上传内核
      uses: actions/upload-artifact@main
      with:
        name: PVE
        path: pve-kernel/*.deb
