name: 测试SSH连接
on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: '编译OpenWrt固件-SSH远程：改为"ssh"打开SSH连接'
        required: true
        default: 'ssh-actions'


jobs:
  build:
    runs-on: ubuntu-22.04
    if: github.event.repository.owner.id == github.event.sender.id
    
    steps:
    - name: 准备结束
      uses: actions/checkout@v2

    - name: 安装依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        #sudo swapoff /swapfile
        sudo rm -rf /swapfile /etc/apt/sources.list.d/* /usr/share/dotnet /usr/local/lib/android /opt/ghc
        #sudo wget -qO - http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg | APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE=1 apt-key add -  
        sudo wget http://download.proxmox.com/debian/proxmox-ve-release-6.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
        sudo chmod +r /etc/apt/trusted.gpg.d/proxmox-ve-release-6.x.gpg
        sudo chmod a+w /etc/apt/sources.list
        sudo -E echo "deb http://download.proxmox.com/debian/pve buster pve-no-subscription" >>/etc/apt/sources.list
        sudo -E apt-get  update
        sudo -E apt-get  install git nano screen patch fakeroot build-essential devscripts libncurses5 libncurses5-dev libssl-dev bc flex bison libelf-dev libaudit-dev libgtk2.0-dev libperl-dev asciidoc xmlto gnupg gnupg2 rsync lintian debhelper libdw-dev libnuma-dev libslang2-dev sphinx-common asciidoc-base automake cpio dh-python file gcc kmod libiberty-dev  libtool perl-modules python3-minimal sed tar zlib1g-dev liblz4-tool idn 
        sudo -E apt-get  autoremove --purge
        sudo -E apt-get  clean

    - name:  安装proxmox依赖
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get install libpve-common-perl  dwarves
        git clone https://github.com/acmel/dwarves.git
        cd dwarves/
        mkdir build
        cd build/
        cmake -D__LIB=lib ..
        sudo make install
        sudo cp pahole /usr/bin/pahole
        #sudo cp -r /usr/local/lib/* /usr/lib/

    - name: 下载源码
      run: 
        git clone git://git.proxmox.com/git/pve-kernel.git pve-kernel
