name: Sync Single Folder

on:
  schedule:
    - cron: '0 * * * *'  # 每小时同步一次
  workflow_dispatch:  # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Sync folder from upstream
        run: |
          git remote add upstream https://github.com/TanZhiwen2001/luci-app-adguardhome.git
          git fetch upstream
          git checkout upstream/main -- luci-app-adguardhome
          git add upstream/main
          git commit -m "Sync folder from upstream"
          git push origin main
