name: 同步更新软件源

on:
  schedule:
    - cron: '0 0 * * 5'  # 每星期五 UTC 时间 00:00 触发
  workflow_dispatch:  # 允许手动触发

jobs:
  sync-folder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "zjt37"
          git config --global user.email "27096491@qq.com"

      - name: Clone target repository
        run: |
          git clone https://${{ secrets.SOURCE_REPO_TOKEN }}@github.com/zjt37/packages.git
          cd packages
          git checkout main  # 切换到目标仓库的分支

      - name: Copy folder from source to target
        run: |
          git clone https://github.com/fw876/helloworld
          rm -r ./helloworld/.github
          rm ./helloworld/LICENSE
          rm ./helloworld/README.md
          cd helloworld
          ls
          

          

